sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # decrypt service-account.json file
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  # auth for google
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-234613
  - gcloud config set compute/zone asia-northeast1-a
  - gcloud container clusters get-credentials multi-cluster
  # auth for docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # build a image for test
  - docker build -t taka5hi/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev
script:
  # execute test
  - docker run taka5hi/react-test npm test -- --coverage
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master